services:
  frontend: # Vite dev server
    image: node:lts-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app:cached
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173" # Vite dev server
    command: sh -c "npm install && npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_HMR_HOST=localhost
    container_name: ft_transcendence_frontend
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5173"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  backend: 
    image: node:lts-alpine
    working_dir: /app
    volumes:
      - ./backend:/app:cached
      - backend_node_modules:/app/node_modules
      - ./backend/database:/app/database
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
    container_name: ft_transcendence_backend
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  nginx: 
    image: nginx:alpine
    ports:
      - "8080:80" # HTTP
    volumes:
      - ./nginx-windows.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    container_name: ft_transcendence_nginx

volumes:
  frontend_node_modules:
  backend_node_modules:
